### ISSUE TITLE
1.0 Fails to load on server

### ISSUE THREAD

**Issue by ezonius** [quaoz/BetterLeads#2]
```
[18:18:52] [main/INFO]: Loading for game Minecraft 1.17.1
[18:18:52] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Mod resolution failed!
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:828) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:195) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:185) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:132) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56) [fabric-server-launch.jar:?]
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Failed to open mod JAR at /pathToJar/betterleads-1.0.0+1.17.1.jar!
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:605) ~[?:?]
	at java.util.concurrent.ForkJoinTask.getException(ForkJoinTask.java:938) ~[?:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:808) ~[fabric-server-launch.jar:?]
	... 11 more
Caused by: java.lang.RuntimeException: Failed to open mod JAR at /pathToJar/betterleads-1.0.0+1.17.1.jar!
	at net.fabricmc.loader.discovery.ModResolver$UrlProcessAction.compute(ModResolver.java:640) ~[fabric-server-launch.jar:?]
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]


```

**Comment by Toilet-Lord** [comment]
Bump that, happens to me too

**Comment by quaoz** [comment]
I think I just uploaded a broken jar to modrinth, should be fixed now.
